name: Build and Deploy Vite React App to Azure Static Web App - movie-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write   # Needed for OIDC login

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # 3️⃣ Install dependencies and build
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # 4️⃣ Deploy to Azure Static Web App
      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # default GitHub token
          action: "upload"
          app_location: "/"          # Root of your repo
          api_location: ""           # Leave empty if no API
          output_location: "dist"    # Vite build output
          skip_app_build: true       # Already built
