name: Build and Deploy Vite React App - movie-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Node 18 for Vite

      # Install dependencies and build
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      # Upload build artifact
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: dist  # ✅ Vite build folder

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write   # Needed for OIDC login
      contents: read

    steps:
      # Checkout repo (optional but good practice)
      - uses: actions/checkout@v4

      # Login to Azure using OIDC
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: false

      # Download the artifact from build job
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./dist

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'movie-app'     # Your Azure Web App name
          slot-name: 'Production'
          package: ./dist           # Vite output folder
