name: Build and Deploy Vite React App to Azure Static Web App - movie-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # Checkout the repo
      - uses: actions/checkout@v4

      # Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Install dependencies and build
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      # Upload build artifact
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: build  # ✅ Vite output folder renamed to 'build'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      # Checkout the repo again
      - uses: actions/checkout@v4

      # Download the build artifact
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: build

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy to Azure Static Web App
      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"            # App root
          output_location: "build"     # ✅ Updated to match Vite build folder
          skip_api_build: true
          app_artifact_location: "build"
          is_static_export: true
